---
title: "Lab 06 - Functions and iterations"
author: "Grace Rieu-Clarke"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}

diamonds %>%
  filter(
    length_mm != 0,
    width_mm != 0,
    depth_mm != 0
  ) %>%
  ggplot(
    mapping = aes(
      x=depth_pct,
      y=length_mm
      )) +
  geom_point(aes(alpha = 0.5))

diamonds %>%
  filter(
    length_mm != 0,
    width_mm != 0,
    depth_mm != 0
  ) %>%
  summary()


```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  filter(width_mm != 0) %>%
  mutate(table_mm = table_pct * width_mm / 100)

diamonds$table_mm %>%
  na.omit() %>%
  mean()


diamonds %>%
  group_by(clarity) %>%
 summarise(mean_tl = mean(table_mm, na.rm = TRUE))






```

_The average table length decreases as clarity increases._

## Exercise 3

_Do derivation on paper, unless you know how to write LaTeX code_


## Exercise 4

```{r}

gmean <- function(x) {
  n = length(x)
  g = exp((1/n)*sum(log(x)))
  return(g)
}

gmean(c(1, 2, 3))


```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples


```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input





# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
